# Generates source/wav_data.c from romfs/*.wav
# Run from 3ds/ directory (or anywhere) after changing sound effects:
#   powershell -ExecutionPolicy Bypass -File tools\gen_wavs.ps1
#
# Requires: PCM16 WAV (fmt=1, bits=16), mono or stereo. Files are embedded
# directly into the binary so no filesystem/romfs access is needed at runtime.

$ErrorActionPreference = "Stop"

$root = if ($PSScriptRoot) { Split-Path -Parent $PSScriptRoot } else { "." }
$romfs = Join-Path $root "romfs"
$outFile = Join-Path $root "source\wav_data.c"

$files = Get-ChildItem -Path $romfs -Filter *.wav | Sort-Object Name
if ($files.Count -eq 0) { throw "no .wav files found in $romfs" }
if ($files.Count -ge 8) { throw "MAX_WAVS is 8 in main.c; found $($files.Count)" }

function Read-WavInfo([string]$path) {
    $b = [IO.File]::ReadAllBytes($path)
    if ($b.Length -lt 44) { throw "$($path): too small" }
    if ([Text.Encoding]::ASCII.GetString($b, 0, 4) -ne "RIFF") { throw "$($path): not RIFF" }
    if ([Text.Encoding]::ASCII.GetString($b, 8, 4) -ne "WAVE") { throw "$($path): not WAVE" }
    $fmt = [BitConverter]::ToUInt16($b, 20)
    $ch = [BitConverter]::ToUInt16($b, 22)
    $bits = [BitConverter]::ToUInt16($b, 34)
    if ($fmt -ne 1)   { throw "$($path): fmt=$fmt (need PCM=1)" }
    if ($bits -ne 16) { throw "$($path): $bits-bit (need PCM16)" }
    if ($ch -lt 1 -or $ch -gt 2) { throw "$($path): channels=$ch" }
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* Generated by tools/gen_wavs.ps1 -- do not edit.")
[void]$sb.AppendLine("   Source of truth: romfs wav files (PCM16). */")
[void]$sb.AppendLine("#include <stdint.h>")

$totalKb = 0
foreach ($f in $files) {
    Read-WavInfo $f.FullName
    $name = [IO.Path]::GetFileNameWithoutExtension($f.Name)
    if ($name -notmatch '^[a-z][a-z0-9_]*$') { throw "$($f.Name): bad identifier" }
    $b = [IO.File]::ReadAllBytes($f.FullName)
    $totalKb += [Math]::Ceiling($b.Length / 1024)
    Write-Host ("  {0,-12} {1,6} B" -f $f.Name, $b.Length)
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("const uint8_t ${name}_wav[$($b.Length)] = {")
    for ($i = 0; $i -lt $b.Length; $i += 20) {
        $endc = [Math]::Min($i + 20, $b.Length) - 1
        $line = ($b[$i..$endc] | ForEach-Object { "0x{0:x2}" -f $_ }) -join ","
        $suffix = if ($endc -lt $b.Length - 1) { "," } else { "" }
        [void]$sb.AppendLine($line + $suffix)
    }
    [void]$sb.AppendLine("};")
}

[void]$sb.AppendLine("")
[void]$sb.AppendLine("struct WavBlob { const char *name; const uint8_t *data; uint32_t len; };")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("const struct WavBlob wav_blobs[] = {")
foreach ($f in $files) {
    $name = [IO.Path]::GetFileNameWithoutExtension($f.Name)
    [void]$sb.AppendLine("    { `"$name`", ${name}_wav, sizeof(${name}_wav) },")
}
[void]$sb.AppendLine("    { 0, 0, 0 }")
[void]$sb.AppendLine("};")

Set-Content -Path $outFile -Value $sb.ToString() -NoNewline
Write-Host "wrote $outFile ($totalKb kB audio, $($files.Count) clips)"
